{% set name = "pyscamp" %}
{% set version = "4.0.3.dev1" %}

package:
  name: {{ name|lower }}-gpu
  version: {{ version }}

source:
  url: https://test-files.pythonhosted.org/packages/27/a6/0ef2219efe44e1fac20a854233f72cf1814ac48c533f480b1451417e88cb/pyscamp-{{ version }}.tar.gz
  sha256: dc448faa1790b2e8174c77bf64bb8f9c6bf607d1767bc7eb81e87e4e947a74e8

build:
  number: 1
  skip: true  # [cuda_compiler_version == "None"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [not win]
    - ninja  # [win]

  host:
    - cuda-version {{ cuda_compiler_version }}
    - python
    - setuptools >=70
    - setuptools-scm
    - pybind11 >=2.13.6
    - eigen 3.4.0
    - cuda-cudart-dev
    - libcufft-dev
    - cuda-cccl

  run:
    - python

test:
  source_files:
    - test
  imports:
    - pyscamp
  commands:
    - pip check
    - cd test
    - python test_pyscamp.py
  requires:
    - pip
    - numpy

about:
  home: https://github.com/zpzim/SCAMP
  summary: SCAlable Matrix Profile
  license: MIT
  license_file:
    - LICENSE
    - third_party/cpu_features/LICENSE

extra:
  recipe-maintainers:
    - zpzim
