{% set name = "pyscamp" %}
{% set version = "3.0.3" %}


package:
  name: {{ name|lower }}-gpu
  version: {{ version }}

source:
  url: https://test-files.pythonhosted.org/packages/1e/7d/04f2935a8e7863346cef8ecd266ca56d4f30dbe2095c2c08d0d1999a3b81/pyscamp-3.0.4.dev9.tar.gz
  sha256: 0f3f7b91fe88a16a79668e3f3ee578524660e121062b8e4534cd40c99454b965
  #url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyscamp-{{ version }}.tar.gz
  #sha256: 047e699f69a087b72af1ea681821d9da37fa3b805abb9ab2396baf6b530a1a11

build:
  number: 1
  skip: True  # [cuda_compiler_version == "None"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [(win64 or linux64) and cuda_compiler_version != "None"]
    - cmake 3.18
    - make  # [not win]
    - jom  # [win]

  host:
    - cudatoolkit
    - python
    - setuptools-scm
    - pybind11 2.9.2
    - eigen 3.4.0

  run:
    - cudatoolkit
    - python


test:
  source_files:
    - test
  imports:
    - pyscamp
  commands:
    - pip check
    - cd test
    - python test_pyscamp.py
  requires:
    - pip
    - numpy

about:
  home: https://github.com/zpzim/SCAMP
  summary: SCAlable Matrix Profile
  license: MIT
  license_file:
    - LICENSE
    - third_party/cpu_features/LICENSE

extra:
  recipe-maintainers:
    - zpzim
