{% set name = "pyscamp" %}
{% set version = "4.0.3.dev3" %}

package:
  name: {{ name|lower }}-gpu
  version: {{ version }}

source:
  url: https://test-files.pythonhosted.org/packages/92/7a/73c8815cf3e5c97fb180ca90f9876a4bbe1e3f325a0ee3de479febf88d0c/pyscamp-{{ version }}.tar.gz
  sha256: 76c78244cf89a3f03f4e6b66c899fc3b81c0e45477a42a34b2819d37ebb93173

build:
  number: 1
  skip: true  # [cuda_compiler_version == "None"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [not win]
    - ninja  # [win]

  host:
    - cuda-version {{ cuda_compiler_version }}
    - python
    - setuptools >=70
    - setuptools-scm
    - pybind11 >=2.13.6
    - eigen 3.4.0
    - cuda-cudart-dev
    - libcufft-dev
    - cuda-cccl

  run:
    - python

test:
  source_files:
    - test
  imports:
    - pyscamp
  commands:
    - pip check
    - cd test
    - python test_pyscamp.py
  requires:
    - pip
    - numpy

about:
  home: https://github.com/zpzim/SCAMP
  summary: SCAlable Matrix Profile
  license: MIT
  license_file:
    - LICENSE
    - third_party/cpu_features/LICENSE

extra:
  recipe-maintainers:
    - zpzim
