{% set name = "pyscamp" %}
{% set version = "4.0.3.dev2" %}

package:
  name: {{ name|lower }}-gpu
  version: {{ version }}

source:
  url: https://test-files.pythonhosted.org/packages/d4/fb/2b951e0d4715e76b93eaac073c0e933282637a0c6cc5f4c36758eb4479c5/pyscamp-{{ version }}.tar.gz
  sha256: 22deae92c097bb054f48177948dbb48639c31f87f2548f330ce8bd34121e27b8

build:
  number: 1
  skip: true  # [cuda_compiler_version == "None"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [not win]
    - ninja  # [win]

  host:
    - cuda-version {{ cuda_compiler_version }}
    - python
    - setuptools >=70
    - setuptools-scm
    - pybind11 >=2.13.6
    - eigen 3.4.0
    - cuda-cudart-dev
    - libcufft-dev
    - cuda-cccl

  run:
    - python

test:
  source_files:
    - test
  imports:
    - pyscamp
  commands:
    - pip check
    - cd test
    - python test_pyscamp.py
  requires:
    - pip
    - numpy

about:
  home: https://github.com/zpzim/SCAMP
  summary: SCAlable Matrix Profile
  license: MIT
  license_file:
    - LICENSE
    - third_party/cpu_features/LICENSE

extra:
  recipe-maintainers:
    - zpzim
