{% set name = "pyscamp" %}
{% set version = "3.0.3" %}


package:
  name: {{ name|lower }}-gpu
  version: {{ version }}

source:
  url: https://test-files.pythonhosted.org/packages/6e/27/67b5fc7298554c1c542be9a46a96e5c3eae8b5b9a16208e9cd5d14ed0c7f/pyscamp-3.0.4.dev2.tar.gz
  sha256: 0ca9f062d544ea5115fed29523350a061e1a968200cc5cd80f7f17f8bc8bcaeb
  #url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyscamp-{{ version }}.tar.gz
  #sha256: 047e699f69a087b72af1ea681821d9da37fa3b805abb9ab2396baf6b530a1a11

build:
  number: 1
  skip: True  # [cuda_compiler_version == "None"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [(win64 or linux64) and cuda_compiler_version != "None"]
    - cmake
    - make  # [not win]
    - ninja  # [win]

  host:
    - cudatoolkit
    - python
    - setuptools-scm
    - pybind11 2.9.2
    - eigen 3.4.0

  run:
    - cudatoolkit
    - python


test:
  source_files:
    - test
  imports:
    - pyscamp
  commands:
    - pip check
    - cd test
    - python test_pyscamp.py
  requires:
    - pip
    - numpy

about:
  home: https://github.com/zpzim/SCAMP
  summary: SCAlable Matrix Profile
  license: MIT
  license_file:
    - LICENSE
    - third_party/cpu_features/LICENSE

extra:
  recipe-maintainers:
    - zpzim
