{% set name = "pyscamp" %}
{% set version = "4.0.1" %}


package:
  name: {{ name|lower }}-gpu
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyscamp-{{ version }}.tar.gz
  sha256: fbdacfbdbd51e319732eafc1ffee2ce0a5e893f9eb610f71ae67d503f3aba66a

build:
  number: 2
  skip: true  # [cuda_compiler_version == "None"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cmake
    - make  # [not win]
    - ninja  # [win]

  host:
    - cuda-version {{ cuda_compiler_version }}
    - python
    - setuptools-scm
    - pybind11 >=2.10
    - eigen 3.4.0
    - cuda-cudart-dev   # [(cuda_compiler_version or "").startswith("12")]
    - libcufft-dev      # [(cuda_compiler_version or "").startswith("12")]

  run:
    - python


test:
  source_files:
    - test
  imports:
    - pyscamp
  commands:
    - pip check
    - cd test
    - python test_pyscamp.py
  requires:
    - pip
    - numpy

about:
  home: https://github.com/zpzim/SCAMP
  summary: SCAlable Matrix Profile
  license: MIT
  license_file:
    - LICENSE
    - third_party/cpu_features/LICENSE

extra:
  recipe-maintainers:
    - zpzim
